import mongoose from "mongoose";

const taskSchema = new mongoose.Schema(
  {
    well: { type: mongoose.Schema.Types.ObjectId, ref: "Well" },
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    title: String,
    description: String,
    priority: { type: String, enum: ["low", "medium", "high"] },
    dueDate: Date,
    status: {
      type: String,
      enum: ["pending", "in-progress", "completed"],
      default: "pending",
    },
    autoGenerated: { type: Boolean, default: false },
    linkedAlert: { type: mongoose.Schema.Types.ObjectId, ref: "Alert" },

    timeline: [
      {
        action: String,
        timestamp: { type: Date, default: Date.now },
        user: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
      },
    ],
  },
  { timestamps: true }
);

export default mongoose.model("Task", taskSchema);