import Task from "../models/Task.js";
import AutoTask from "../models/AutoTask.js";

export const approveAutoTask = async (id) => {
  const autoTask = await AutoTask.findById(id);

  const task = await Task.create({
    well: autoTask.well,
    autoGenerated: true,
    title: autoTask.reason,
    description: `Auto-generated maintenance: Risk ${autoTask.riskScore}`,
    priority: "high",
  });

  autoTask.status = "approved";
  await autoTask.save();

  return task;
};

export const rejectAutoTask = async (id) => {
  return await AutoTask.findByIdAndUpdate(id, { status: "rejected" });
};