import Alert from "../models/Alert.js";
import AutoTask from "../models/AutoTask.js";
import Task from "../models/Task.js";
import { createAlert, shouldTriggerAutoTask } from "../services/alertService.js";

export const getAllAlerts = async (req, res) => {
  const alerts = await Alert.find().sort({ createdAt: -1 });
  res.json(alerts);
};

export const getAlertDetails = async (req, res) => {
  const alert = await Alert.findById(req.params.id);
  res.json(alert);
};

export const markRead = async (req, res) => {
  await Alert.findByIdAndUpdate(req.params.id, { read: true });
  res.json({ message: "Alert marked as read" });
};

// Create alert and trigger auto task if needed (only one auto task per alert)
export const createAlertAndMaybeAutoTask = async (req, res) => {
  const alert = await createAlert(req.body);
  let autoTask = null;
  if (shouldTriggerAutoTask(alert)) {
    // Prevent duplicate auto tasks for the same alert
    autoTask = await AutoTask.findOne({ well: alert.well, reason: alert.message, status: { $ne: "rejected" } });
    if (!autoTask) {
      autoTask = await AutoTask.create({
        well: alert.well,
        riskScore: 80,
        reason: alert.message,
        predictedDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        status: "pending",
      });
    }
  }
  res.json({ alert, autoTask });
};

// When user accepts alert, create a Task (not AutoTask), link to alert, and approve AutoTask
export const acceptAlertAndCreateTask = async (req, res) => {
  const alert = await Alert.findById(req.params.id);
  if (!alert) return res.status(404).json({ message: "Alert not found" });
  await Alert.findByIdAndUpdate(req.params.id, { read: true });
  // Find related auto task
  const autoTask = await AutoTask.findOne({ well: alert.well, reason: alert.message, status: { $ne: "rejected" } });
  if (autoTask) {
    autoTask.status = "approved";
    await autoTask.save();
  }
  // Create the actual Task
  const task = await Task.create({
    well: alert.well,
    autoGenerated: true,
    title: alert.type || "Alert Response",
    description: alert.message,
    priority: "high",
    linkedAlert: alert._id,
  });
  res.json({ message: "Alert accepted and task created", task });
};

// When user rejects alert, mark auto task as rejected
export const rejectAlertAndAutoTask = async (req, res) => {
  const alert = await Alert.findById(req.params.id);
  if (!alert) return res.status(404).json({ message: "Alert not found" });
  await Alert.findByIdAndUpdate(req.params.id, { read: true });
  // Find related auto task
  const autoTask = await AutoTask.findOne({ well: alert.well, reason: alert.message, status: { $ne: "rejected" } });
  if (autoTask) {
    autoTask.status = "rejected";
    await autoTask.save();
  }
  res.json({ message: "Alert rejected and auto task marked as rejected" });
};