import Task from "../models/Task.js";

// Get all tasks (with populated references)
export const getTasks = async (req, res) => {
  try {
    const tasks = await Task.find()
      .populate("assignedTo", "name firstName lastName email role")
      .populate("well", "name location status")
      .populate("createdBy", "name firstName lastName")
      .sort({ createdAt: -1 });
    res.json(tasks);
  } catch (error) {
    console.error("getTasks error:", error);
    res.status(500).json({ message: "Server error while fetching tasks" });
  }
};

// Create a new task
export const createTask = async (req, res) => {
  try {
    const { title, description, priority, assignedTo, well, status, autoGenerated, dueDate } = req.body;

    if (!title || !description) {
      return res.status(400).json({ message: "Title and description are required" });
    }

    const taskData = {
      title,
      description,
      priority: priority || "medium",
      status: status || "pending",
      autoGenerated: autoGenerated || false,
    };

    // Set createdBy if user is authenticated
    if (req.user) {
      taskData.createdBy = req.user._id;
    }

    // Only set optional refs if they have a value (avoid empty string → CastError)
    if (assignedTo && assignedTo.length > 0) {
      taskData.assignedTo = assignedTo;
    }
    if (well && well.length > 0) {
      taskData.well = well;
    }
    if (dueDate) {
      taskData.dueDate = dueDate;
    }

    const task = await Task.create(taskData);

    // Populate before returning
    const populated = await Task.findById(task._id)
      .populate("assignedTo", "name firstName lastName email role")
      .populate("well", "name location status")
      .populate("createdBy", "name firstName lastName");

    res.status(201).json(populated);
  } catch (error) {
    console.error("createTask error:", error);
    if (error.name === "ValidationError") {
      return res.status(400).json({ message: error.message });
    }
    res.status(500).json({ message: "Server error while creating task" });
  }
};

// Get single task details
export const getTaskDetails = async (req, res) => {
  try {
    const task = await Task.findById(req.params.id)
      .populate("assignedTo", "name firstName lastName email role")
      .populate("well", "name location status")
      .populate("createdBy", "name firstName lastName");

    if (!task) {
      return res.status(404).json({ message: "Task not found" });
    }

    res.json(task);
  } catch (error) {
    console.error("getTaskDetails error:", error);
    res.status(500).json({ message: "Server error while fetching task details" });
  }
};

// Update a task
export const updateTask = async (req, res) => {
  try {
    const task = await Task.findById(req.params.id);

    if (!task) {
      return res.status(404).json({ message: "Task not found" });
    }

    // Clean up empty string references to avoid CastError
    const updateData = { ...req.body };
    if (updateData.assignedTo === "") delete updateData.assignedTo;
    if (updateData.well === "") delete updateData.well;

    const updated = await Task.findByIdAndUpdate(req.params.id, updateData, {
      new: true,
      runValidators: true,
    })
      .populate("assignedTo", "name firstName lastName email role")
      .populate("well", "name location status")
      .populate("createdBy", "name firstName lastName");

    res.json(updated);
  } catch (error) {
    console.error("updateTask error:", error);
    if (error.name === "ValidationError") {
      return res.status(400).json({ message: error.message });
    }
    res.status(500).json({ message: "Server error while updating task" });
  }
};

// Delete a task by ID
export const deleteTask = async (req, res) => {
  try {
    const task = await Task.findById(req.params.id);

    if (!task) {
      return res.status(404).json({ message: "Task not found" });
    }

    await task.deleteOne();

    res.json({ message: "Task deleted successfully", taskId: req.params.id });
  } catch (error) {
    console.error("deleteTask error:", error);
    res.status(500).json({ message: "Server error while deleting task" });
  }
};
