import React, { useState, useEffect, useContext } from 'react';
import axios from 'axios';
import { AuthContext } from '../context/AuthContext';
import { Activity, Check, X, BrainCircuit, CalendarClock, Trash2 } from 'lucide-react';
import toast from 'react-hot-toast';

export const AutoTasksApproval = () => {
  const { user } = useContext(AuthContext);
  const [autoTasks, setAutoTasks] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAutoTasks();
  }, []);

  const fetchAutoTasks = async () => {
    try {
      setLoading(true);
      const res = await axios.get('/api/tasks/auto');
      setAutoTasks(res.data);
    } catch (err) {
      toast.error('Failed to load predictive tasks');
    } finally {
      setLoading(false);
    }
  };

  const handleAction = async (id, action) => {
    try {
      await axios.post(`/api/tasks/auto/${id}/${action}`);
      toast.success(`Task ${action} successfully`);
      fetchAutoTasks();
    } catch (err) {
      toast.error(`Failed to ${action} task`);
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm('Delete this auto task permanently?')) {
      try {
        await axios.delete(`/api/tasks/auto/${id}`);
        toast.success('Auto task deleted successfully');
        fetchAutoTasks();
      } catch (err) {
        toast.error('Failed to delete auto task');
      }
    }
  };

  if (loading) return <div className="p-10 flex justify-center"><div className="animate-spin w-8 h-8 border-2 border-aqua border-t-transparent rounded-full"></div></div>;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center glass p-6 rounded-2xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-aqua/5 blur-[50px] rounded-full"></div>
        <div className="relative z-10 w-full">
          <h1 className="text-2xl font-bold text-gray-100 flex items-center mb-1">
            <BrainCircuit className="w-6 h-6 mr-3 text-aqua animate-pulse" />
            AI Predictive Tasks
          </h1>
          <p className="text-gray-400 text-sm">Review maintenance tasks generated by continuous data monitoring</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 lg:gap-6 gap-4">
        {autoTasks.length === 0 ? (
          <div className="col-span-full glass p-12 rounded-2xl text-center flex flex-col items-center">
            <Activity className="w-16 h-16 text-aqua mb-4 opacity-50" />
            <h3 className="text-xl font-medium text-gray-200">No AI Tasks</h3>
            <p className="text-gray-500 mt-2">The system will alert you when proactive maintenance is recommended.</p>
          </div>
        ) : (
          autoTasks.map((task) => (
            <div key={task._id} className="glass p-6 rounded-2xl flex flex-col justify-between border-t border-t-aqua/20 shadow-[0_4px_20px_rgba(0,247,255,0.05)] hover:shadow-[0_8px_30px_rgba(0,247,255,0.1)] transition-all">
              <div>
                <div className="flex justify-between items-start mb-4">
                  <div className="bg-aqua/10 text-aqua border border-aqua/30 px-3 py-1 rounded-full text-xs font-semibold tracking-wider flex items-center gap-2">
                    <Activity className="w-3 h-3" />
                    RISK SCORE: <span className="text-white text-sm">{task.riskScore}</span>/100
                  </div>
                  <span className="text-xs text-gray-500 flex items-center gap-1">
                    <CalendarClock className="w-3 h-3"/>
                    Generated {new Date(task.createdAt).toLocaleDateString()}
                  </span>
                </div>
                
                <h3 className="text-lg font-bold text-gray-100 mb-2 flex flex-wrap gap-2 items-center">
                  Predicted Maintenance Required
                  {task.status === 'approved' && <span className="text-[10px] px-2 py-0.5 uppercase tracking-widest rounded bg-green-500/10 text-green-400 border border-green-500/50">Approved</span>}
                  {task.status === 'rejected' && <span className="text-[10px] px-2 py-0.5 uppercase tracking-widest rounded bg-red-500/10 text-red-400 border border-red-500/50">Rejected</span>}
                  {task.status === 'pending' && <span className="text-[10px] px-2 py-0.5 uppercase tracking-widest rounded bg-amber-500/10 text-amber-400 border border-amber-500/50">Pending</span>}
                </h3>
                <p className="text-gray-400 text-sm leading-relaxed mb-4">{task.reason}</p>
                
                <div className="bg-dark-bg/60 rounded-xl p-3 border border-dark-border mb-6">
                  <p className="text-xs text-gray-500 mb-1 font-medium uppercase tracking-wider">Suggested Action Date</p>
                  <p className="text-sm font-semibold text-amber-400">{new Date(task.predictedDate).toDateString()}</p>
                </div>
              </div>

              {user?.role === 'admin' && (
                <>
                  {task.status === 'pending' ? (
                    <div className="flex space-x-3 mt-auto">
                      <button 
                        onClick={() => handleAction(task._id, 'approve')}
                        className="flex-1 bg-aqua/20 text-aqua border border-aqua/50 hover:bg-aqua hover:text-dark-bg transition-colors py-2 rounded-xl flex justify-center items-center font-bold tracking-wide shadow-[0_0_15px_rgba(0,247,255,0.2)]"
                      >
                        <Check className="w-4 h-4 mr-2" />
                        Accept & Create Task
                      </button>
                      <button 
                        onClick={() => handleAction(task._id, 'reject')}
                        className="bg-dark-bg text-gray-400 border border-dark-border hover:bg-red-500/10 hover:text-red-400 hover:border-red-500/30 transition-colors px-4 py-2 rounded-xl flex justify-center items-center"
                      >
                        <X className="w-4 h-4" />
                      </button>
                      <button 
                        onClick={() => handleDelete(task._id)}
                        className="bg-dark-bg text-gray-400 border border-dark-border hover:bg-red-500/10 hover:text-red-400 hover:border-red-500/30 transition-colors px-3 py-2 rounded-xl flex justify-center items-center"
                        title="Delete Auto Task"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  ) : (
                    <div className="flex items-center justify-between mt-auto pt-2">
                      <span className="text-sm text-gray-500 font-medium">
                        Reviewed & {task.status === 'approved' ? 'Converted to Task' : 'Dismissed'}
                      </span>
                      <button 
                        onClick={() => handleDelete(task._id)}
                        className="text-gray-600 hover:text-red-400 transition-colors p-1.5 rounded-lg hover:bg-red-500/10"
                        title="Delete Auto Task"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  )}
                </>
              )}
            </div>
          ))
        )}
      </div>
    </div>
  );
};
