import React, { useState, useEffect, useContext } from 'react';
import axios from 'axios';
import { AuthContext } from '../context/AuthContext';
import { Plus, Trash2, Edit2, CheckCircle, Clock, Activity, X } from 'lucide-react';
import toast from 'react-hot-toast';

export const TasksList = () => {
  const { user } = useContext(AuthContext);
  const [tasks, setTasks] = useState([]);
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);

  // Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingTask, setEditingTask] = useState(null);
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    priority: 'medium',
    assignedTo: ''
  });

  useEffect(() => {
    fetchTasks();
    fetchUsers();
  }, []);

  const fetchTasks = async () => {
    try {
      setLoading(true);
      const res = await axios.get('/api/tasks');
      setTasks(res.data);
    } catch (err) {
      toast.error('Failed to load tasks');
    } finally {
      setLoading(false);
    }
  };

  const fetchUsers = async () => {
    try {
      const res = await axios.get('/api/auth/users');
      setUsers(res.data);
    } catch (err) {
      console.error('Failed to load users for assignment');
    }
  };

  const handleDelete = async (id) => {
    if (window.confirm("Delete this task?")) {
      try {
        await axios.delete(`/api/tasks/${id}`);
        toast.success('Task deleted successfully');
        fetchTasks();
      } catch (err) {
        toast.error('Failed to delete task');
      }
    }
  };

  const handleStatusChange = async (id, status) => {
    try {
      await axios.put(`/api/tasks/${id}`, { status });
      toast.success('Task status updated successfully');
      fetchTasks();
    } catch(err) {
      toast.error('Failed to update task status');
    }
  };

  const getStatusBadge = (status) => {
    switch (status) {
      case 'completed': return <span className="bg-green-500/20 text-green-400 border border-green-500/30 px-3 py-1 rounded-full text-xs flex items-center gap-1"><CheckCircle className="w-3 h-3"/> Completed</span>;
      case 'in-progress': return <span className="bg-amber-500/20 text-amber-400 border border-amber-500/30 px-3 py-1 rounded-full text-xs flex items-center gap-1"><Activity className="w-3 h-3"/> In Progress</span>;
      default: return <span className="bg-gray-500/20 text-gray-400 border border-gray-500/30 px-3 py-1 rounded-full text-xs flex items-center gap-1"><Clock className="w-3 h-3"/> Pending</span>;
    }
  };

  // Status transition logic
  const getAvailableStatuses = (currentStatus) => {
    if (currentStatus === 'completed') return [{ value: 'completed', label: 'Completed' }];
    if (currentStatus === 'in-progress') return [
      { value: 'in-progress', label: 'In Progress' },
      { value: 'completed', label: 'Completed' }
    ];
    return [
      { value: 'pending', label: 'Pending' },
      { value: 'in-progress', label: 'In Progress' },
      { value: 'completed', label: 'Completed' }
    ];
  };

  // Form handling
  const openCreateModal = () => {
    setEditingTask(null);
    setFormData({ title: '', description: '', priority: 'medium', assignedTo: '' });
    setIsModalOpen(true);
  };

  const openEditModal = (task) => {
    setEditingTask(task);
    setFormData({
      title: task.title || '',
      description: task.description || '',
      priority: task.priority || 'medium',
      assignedTo: task.assignedTo?._id || task.assignedTo || ''
    });
    setIsModalOpen(true);
  };

  const handleFormChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value});
  };

  const handleFormSubmit = async (e) => {
    e.preventDefault();
    try {
      if (editingTask) {
        await axios.put(`/api/tasks/${editingTask._id}`, formData);
        toast.success("Task updated successfully");
      } else {
        await axios.post('/api/tasks', { ...formData, status: 'pending', autoGenerated: false });
        toast.success("Task created successfully");
      }
      setIsModalOpen(false);
      fetchTasks();
    } catch(err) {
      toast.error(`Failed to ${editingTask ? 'update' : 'create'} task`);
    }
  };

  if (loading && tasks.length === 0) return <div className="p-10 flex justify-center"><div className="animate-spin w-8 h-8 border-2 border-aqua border-t-transparent rounded-full"></div></div>;

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center bg-dark-card p-6 rounded-2xl border border-dark-border glass relative z-0">
        <div>
          <h1 className="text-2xl font-bold font-sans text-gray-100">Tasks Management</h1>
          <p className="text-gray-400 text-sm mt-1">View and manage maintenance tasks</p>
        </div>
        <button onClick={openCreateModal} className="glass-button px-4 py-2 rounded-xl flex items-center space-x-2 font-medium">
          <Plus className="w-5 h-5" />
          <span>New Task</span>
        </button>
      </div>

      <div className="glass rounded-2xl overflow-hidden shadow-2xl relative z-0">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-dark-bg/60 border-b border-dark-border text-gray-400 text-sm uppercase tracking-wider">
                <th className="p-4 font-medium">Title</th>
                <th className="p-4 font-medium">Priority</th>
                <th className="p-4 font-medium flex-nowrap whitespace-nowrap">Assigned To</th>
                <th className="p-4 font-medium">Status</th>
                <th className="p-4 font-medium">Auto Gen</th>
                <th className="p-4 font-medium">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-dark-border">
              {tasks.length === 0 ? (
                <tr>
                  <td colSpan="6" className="p-8 text-center text-gray-500">
                    No tasks found.
                  </td>
                </tr>
              ) : (
                tasks.map((task) => {
                  const availableStatuses = getAvailableStatuses(task.status);
                  
                  // Permissions Logic:
                  const isAssignedToMe = task.assignedTo?._id === user._id || task.assignedTo === user._id;
                  const isAdmin = user?.role === 'admin';
                  const canModify = isAdmin || isAssignedToMe;
                  
                  const isCompleted = task.status === 'completed';
                  const isUnassigned = !task.assignedTo;
                  
                  const disableStatusChange = 
                    isCompleted || 
                    !canModify || 
                    (!isAdmin && isUnassigned && task.status === 'pending');
                    
                  const disableActions = !canModify;

                  return (
                    <tr key={task._id} className="hover:bg-dark-bg/40 transition-colors">
                      <td className="p-4">
                        <p className="font-semibold text-gray-200">{task.title}</p>
                        <p className="text-sm text-gray-500 line-clamp-1 max-w-xs">{task.description}</p>
                      </td>
                      <td className="p-4">
                        <span className={`px-2 py-1 rounded text-xs uppercase font-bold tracking-wider 
                          ${task.priority === 'high' ? 'text-red-400 bg-red-400/10' : 
                            task.priority === 'medium' ? 'text-amber-400 bg-amber-400/10' : 'text-blue-400 bg-blue-400/10'}`}>
                          {task.priority || 'Normal'}
                        </span>
                      </td>
                      <td className="p-4 text-sm text-gray-300 whitespace-nowrap">
                        {task.assignedTo?.name || <span className="text-gray-600">Unassigned</span>}
                      </td>
                      <td className="p-4">
                        {getStatusBadge(task.status)}
                      </td>
                      <td className="p-4 text-gray-400 text-sm">
                        {task.autoGenerated ? <span className="text-aqua border border-aqua/30 bg-aqua/10 px-2 py-1 rounded text-xs">AI Generated</span> : 'Manual'}
                      </td>
                      <td className="p-4">
                        <div className="flex items-center space-x-3">
                          <select 
                            className={`bg-dark-bg border border-dark-border text-xs rounded-lg px-2 py-1 text-gray-300 outline-none focus:border-aqua ${disableStatusChange ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}`}
                            value={task.status}
                            disabled={disableStatusChange}
                            onChange={(e) => handleStatusChange(task._id, e.target.value)}
                            title={isUnassigned && task.status === 'pending' ? "Assign a user to change status" : ""}
                          >
                            {availableStatuses.map(s => (
                               <option key={s.value} value={s.value}>{s.label}</option>
                            ))}
                          </select>
                          <button 
                            onClick={() => openEditModal(task)} 
                            className={`transition-colors ${disableActions ? 'text-gray-700 cursor-not-allowed' : 'text-gray-500 hover:text-aqua'}`} 
                            title="Edit Task"
                            disabled={disableActions}
                          >
                             <Edit2 className="w-4 h-4" />
                          </button>
                          <button 
                            onClick={() => handleDelete(task._id)} 
                            className={`transition-colors ${disableActions ? 'text-gray-700 cursor-not-allowed' : 'text-gray-500 hover:text-red-400'}`} 
                            title="Delete Task"
                            disabled={disableActions}
                          >
                             <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  )
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Task Modal Overlay */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4 animate-fade-in">
          <div className="bg-dark-card border border-dark-border shadow-2xl rounded-2xl w-full max-w-lg overflow-hidden relative">
            <div className="flex justify-between items-center p-6 border-b border-dark-border bg-dark-bg/50">
               <h2 className="text-xl font-bold text-gray-100">{editingTask ? 'Edit Task' : 'Create New Task'}</h2>
               <button onClick={() => setIsModalOpen(false)} className="text-gray-500 hover:text-gray-200 transition-colors">
                  <X className="w-6 h-6" />
               </button>
            </div>
            
            <form onSubmit={handleFormSubmit} className="p-6 space-y-4">
              <div>
                 <label className="block text-sm font-medium text-gray-400 mb-1">Title</label>
                 <input 
                   type="text" 
                   name="title" 
                   value={formData.title} 
                   onChange={handleFormChange} 
                   required
                   className="w-full px-4 py-2 bg-dark-bg border border-dark-border rounded-lg text-gray-200 focus:outline-none focus:border-aqua transition-colors"
                   placeholder="e.g. Inspect Well Pump"
                 />
              </div>

              <div>
                 <label className="block text-sm font-medium text-gray-400 mb-1">Description</label>
                 <textarea 
                   name="description" 
                   value={formData.description} 
                   onChange={handleFormChange} 
                   required
                   rows="3"
                   className="w-full px-4 py-2 bg-dark-bg border border-dark-border rounded-lg text-gray-200 focus:outline-none focus:border-aqua transition-colors"
                   placeholder="Detailed task description..."
                 />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-400 mb-1">Priority</label>
                  <select 
                    name="priority" 
                    value={formData.priority} 
                    onChange={handleFormChange}
                    className="w-full px-4 py-2 bg-dark-bg border border-dark-border rounded-lg text-gray-200 focus:outline-none focus:border-aqua transition-colors appearance-none"
                  >
                    <option value="low">Low</option>
                    <option value="medium">Medium</option>
                    <option value="high">High</option>
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-400 mb-1">Assign To</label>
                  <select 
                    name="assignedTo" 
                    value={formData.assignedTo} 
                    onChange={handleFormChange}
                    className="w-full px-4 py-2 bg-dark-bg border border-dark-border rounded-lg text-gray-200 focus:outline-none focus:border-aqua transition-colors appearance-none"
                  >
                    <option value="">-- Unassigned --</option>
                    {users.filter(u => u.role === 'officer').map(u => (
                      <option key={u._id} value={u._id}>{u.name}</option>
                    ))}
                  </select>
                </div>
              </div>

              <div className="pt-4 flex justify-end gap-3 mt-4">
                 <button 
                   type="button" 
                   onClick={() => setIsModalOpen(false)}
                   className="px-4 py-2 rounded-xl text-gray-400 hover:text-gray-200 hover:bg-dark-border transition-colors font-medium"
                 >
                   Cancel
                 </button>
                 <button 
                   type="submit" 
                   className="glass-button px-6 py-2 rounded-xl font-medium shadow-lg"
                 >
                   {editingTask ? 'Save Changes' : 'Create Task'}
                 </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
